schoolmate/src/main/java/com/spring/schoolmate/entity/Product.java, schoolmate/src/main/java/com/spring/schoolmate/entity/ProductExchange.java
=> [Docs] KAN-17 Product entity 수정

schoolmate/.gitignore, schoolmate/src/main/java/com/spring/schoolmate/entity/ExternalAccount.java
=> [Feat] KAN-23 ExternalAccount 작성

schoolmate/src/main/java/com/spring/schoolmate/entity/Role.java
jira : KAN-16
- @Column name :: 통일성 위해 추가
=> [Feat] KAN-16 Role 수정

schoolmate/src/main/java/com/spring/schoolmate/entity/Allergy.java, schoolmate/src/main/java/com/spring/schoolmate/entity/StudentAllergy.java
jira : KAN-16
- @Column name :: 통일성 위해 추가
=> Feat :: KAN-20 Allergy, StudentAllergy Entity 수정

schoolmate/src/main/java/com/spring/schoolmate/entity/Allergy.java, schoolmate/src/main/java/com/spring/schoolmate/entity/Mission.java, schoolmate/src/main/java/com/spring/schoolmate/entity/PointHistory.java, schoolmate/src/main/java/com/spring/schoolmate/entity/Profile.java, schoolmate/src/main/java/com/spring/schoolmate/entity/Role.java, schoolmate/src/main/java/com/spring/schoolmate/entity/Student.java, schoolmate/src/main/java/com/spring/schoolmate/entity/StudentAllergy.java
=> Feat :: 전체 코드 수정

schoolmate/src/main/java/com/spring/schoolmate/entity/Student.java
=> [Feat]  KAN-13 Student Entity 수정

schoolmate/src/main/java/com/spring/schoolmate/entity/ExternalAccount.java, schoolmate/src/main/java/com/spring/schoolmate/repository/AllergyRepository.java, schoolmate/src/main/java/com/spring/schoolmate/repository/ExternalAccountRepository.java, schoolmate/src/main/java/com/spring/schoolmate/repository/MissionRepository.java, schoolmate/src/main/java/com/spring/schoolmate/repository/PointHistoryRepository.java, schoolmate/src/main/java/com/spring/schoolmate/repository/ProfileRepository.java, schoolmate/src/main/java/com/spring/schoolmate/repository/RoleRepository.java, schoolmate/src/main/java/com/spring/schoolmate/repository/StudentAllergyRepository.java, schoolmate/src/main/java/com/spring/schoolmate/repository/StudentRepository.java
jira : KAN-26
- Entity Class 필드명과 Repository의 메소드 인자값 명이 알맞게 잘 들어갔는지 체크 필요
=> Feat :: KAN-26 Repository 작성

schoolmate/src/main/java/com/spring/schoolmate/exception/NotFoundException.java, schoolmate/src/main/java/com/spring/schoolmate/repository/ProductRepository.java, schoolmate/src/main/java/com/spring/schoolmate/service/ProductService.java
jira : KAN-28
- ProductService
-  상품 등록, 상품 수정, 특정 상품 삭제, 상품 조회, 재고가 0인 상품 삭제
=> [Feat] KAN-28 ProductRepository, ProductService 구현

schoolmate/src/main/java/com/spring/schoolmate/controller/ProductController.java, schoolmate/src/main/java/com/spring/schoolmate/controller/ProductExchangeController.java
=> [Feat] KAN-36 ProductController, ProductExchangeController 구현

schoolmate/build.gradle, schoolmate/src/main/java/com/spring/schoolmate/advice/DefaultExceptionAdvice.java, schoolmate/src/main/java/com/spring/schoolmate/config/AdminInitializer.java, schoolmate/src/main/java/com/spring/schoolmate/config/SecurityConfig.java, schoolmate/src/main/java/com/spring/schoolmate/controller/PointHistoryController.java, schoolmate/src/main/java/com/spring/schoolmate/dto/admin/AdminReq.java, schoolmate/src/main/java/com/spring/schoolmate/dto/admin/AdminRes.java, schoolmate/src/main/java/com/spring/schoolmate/entity/Admin.java, schoolmate/src/main/java/com/spring/schoolmate/entity/Role.java, schoolmate/src/main/java/com/spring/schoolmate/entity/Student.java, schoolmate/src/main/java/com/spring/schoolmate/jwt/JWTFilter.java, schoolmate/src/main/java/com/spring/schoolmate/jwt/JWTUtil.java, schoolmate/src/main/java/com/spring/schoolmate/jwt/LoginFilter.java, schoolmate/src/main/java/com/spring/schoolmate/jwt/OAuth2SuccessHandler.java, schoolmate/src/main/java/com/spring/schoolmate/repository/AdminRepository.java, schoolmate/src/main/java/com/spring/schoolmate/security/CustomAdminDetailService.java, schoolmate/src/main/java/com/spring/schoolmate/security/CustomAdminDetails.java, schoolmate/src/main/java/com/spring/schoolmate/security/OAuth2CustomUser.java, schoolmate/src/main/java/com/spring/schoolmate/service/AdminService.java, schoolmate/src/main/java/com/spring/schoolmate/service/CustomOAuth2UserService.java, schoolmate/src/main/java/com/spring/schoolmate/service/PointHistoryService.java, schoolmate/src/main/java/com/spring/schoolmate/service/StudentService.java, schoolmate/src/main/resources/application.yml
=> [Feat] KAN-36 Admin 추가

schoolmate/src/main/java/com/spring/schoolmate/controller/ProfileController.java, schoolmate/src/main/java/com/spring/schoolmate/controller/SchoolController.java, schoolmate/src/main/java/com/spring/schoolmate/dto/profile/ProfileUpdateReq.java, schoolmate/src/main/java/com/spring/schoolmate/entity/Profile.java, schoolmate/src/main/java/com/spring/schoolmate/jwt/LoginFilter.java, schoolmate/src/main/java/com/spring/schoolmate/service/ProfileService.java
=> Fix :: KAN-35, KAN-36, KAN-38 수정

schoolmate/src/main/java/com/spring/schoolmate/jwt/LoginFilter.java
=> [Chore] KAN-42 중복코드 제거

schoolmate/src/main/java/com/spring/schoolmate/dto/product/ProductRes.java, schoolmate/src/main/java/com/spring/schoolmate/entity/Product.java, schoolmate/src/main/java/com/spring/schoolmate/service/ProductService.java
jira : KAN-28
- Date -> LocalDateTime으로 수정
=> [Chore] KAN-28 Product 로직 수정

schoolmate/src/main/java/com/spring/schoolmate/controller/SchoolSearchController.java, schoolmate/src/main/java/com/spring/schoolmate/dto/neis/ClassInfoRow.java, schoolmate/src/main/java/com/spring/schoolmate/dto/neis/SchoolMajorRow.java, schoolmate/src/main/java/com/spring/schoolmate/service/NeisApiService.java
학교 검색 프로세스에서 일반고등학교 외 특수목적고등학교의 경우 학과마다 반의 수가 다르기 때문에
이를 받아올 수 있도록 수정
=> [Fix] KAN-36 Controller 수정

schoolmate/src/main/java/com/spring/schoolmate/service/ProductService.java
=> [Feat] KAN-28 ProductService 상품 카테고리 조건 추가

schoolmate/src/main/java/com/spring/schoolmate/controller/FileUploadController.java, schoolmate/src/main/java/com/spring/schoolmate/dto/eatphoto/EatPhotoRes.java, schoolmate/src/main/java/com/spring/schoolmate/service/EatPhotoService.java, schoolmate/src/main/java/com/spring/schoolmate/service/FirebaseStorageService.java, schoolmate/src/main/java/com/spring/schoolmate/service/PointHistoryService.java
jira : KAN-37
- Google Cloud Vision AI 연결 시도 전 프로젝트 터미널에서
- 환경 변수 설정 (정확한 이름 확인)
export GOOGLE_APPLICATION_CREDENTIALS="/Users/j.y/Desktop/cloudvision/green-tract-473106-b3-c17ff3abb9c9.json"
- 환경 변수가 제대로 설정되었는지 확인 (선택 사항)
echo $GOOGLE_APPLICATION_CREDENTIALS 
- 같은 터미널에서 서버 실행 (예시)
./gradlew bootRun
=> [Feat] KAN-37 급식 사진 업로드 Google Cloud Vision AI 연결

schoolmate/src/main/java/com/spring/schoolmate/controller/PointHistoryController.java, schoolmate/src/main/java/com/spring/schoolmate/controller/StudentController.java, schoolmate/src/main/java/com/spring/schoolmate/service/PointHistoryService.java
jira : KAN-48
- StudentController 추가
- 로그인된 학생의 현재 보유 포인트를 조회. (authToken 기반)
- 교환 후 포인트 잔액을 업데이트 하는 메서드 추가
=> [Feat] KAN-48  상품 교환 API 연결 응답 처리 구현

schoolmate/src/main/java/com/spring/schoolmate/controller/PointHistoryController.java
jira : KAN-38
- 로그인된 학생의 모든 포인트 거래 내역을 최신순으로 조회. (authToken 기반)
=> [Feat] KAN-38 PointHistoryController 메서드 추가

schoolmate/src/main/java/com/spring/schoolmate/controller/AuthController.java, schoolmate/src/main/java/com/spring/schoolmate/service/AuthService.java
=> [Feat] KAN-36, KAN-35 :: 회원가입 부분 수정

schoolmate/src/main/java/com/spring/schoolmate/controller/SchoolController.java
기존 학교 시간표 불러올때 시작일, 종료일 만 요청했으나 
조회 기준 날짜 (YYYY-MM-DD 형식)으로 변경
=> [Fix] KAN-41 수정

schoolmate/src/main/java/com/spring/schoolmate/service/ProductService.java
=> [Feat] KAN-28 상품 수정 로직 수정
